### ISSUE TITLE
Appveyor webhook

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/ccafs#27]
I wonder whether deliveries fail for this repo because of git remote or repo transfer, maybe have a look before emailing them? Sorry about that!

**Comment by maelle** [comment]
Maybe try that first (email received this night from Appveyor)

* New commit and push (the "account" was blocked, unclear to me whether they mean Appveyor or GitHub...)

*  If you believe that you need to re-create webhook, you can find correct Webhook URL on General project settings in AppVeyor UI. Use it when creating a Webhook on GitHub. Select “Push” and “Pull request” events. You can also delete unneeded webhook manually on GitHub. Or you can create new project on AppVeyor and correct webhook will be created automatically.

 *   If repo owner changed, you can may also need to re-authorize GitHub at https://ci.appveyor.com/account.

**Comment by sckott** [comment]
should be fixed . now
